Format Haskell with fourmolu and elm with elm-format
tweag/servant-template pull request #34
Opened 2022-06-03 17:06 UTC by cgeorgii

`fourmolu` instead of `ormolu` because it looks more like Elm.

2022-06-07 06:38 UTC, aspiwack commented
Use Ormolu, not Fourmolu. Rationale: this is what we use, and it's not a conversation that I want projects to spend time on.

2022-06-07 08:12 UTC, marcosh requested changes
I really value having the imports separated by package, with the package explicitly mentioned.

Is there a way, both for `elm-format` and `ormolu`, to specify that imports should not be touched?

2022-06-07 08:12 UTC, marcosh commented on README.md
> +The Haskell files are formatted using `fourmolu`. The configuration is found in `fourmolu.yaml`.
shouldn't it be `ormolu`?

2022-06-07 08:12 UTC, marcosh commented on spec/InMemoryContentRepository.hs
>  -- containers
these comments make no sense now and should be removed manually

2022-06-07 08:12 UTC, marcosh commented on README.md
> +There is a script to format all files in the codebase (Elm and Haskell) under `bin/format`.
would be nice to have (also) two separate scripts for `Elm` and `Haskell`

2022-06-16 12:17 UTC, cgeorgii commented
@marcosh No, unfortunately they are both opinionated and won't allow for configuration. I personally don't see the value of adding the package name to the import list, as it adds more noise than useful information.

2022-11-07 14:12 UTC, marcosh commented
> @marcosh No, unfortunately they are both opinionated and won't allow for configuration. I personally don't see the value of adding the package name to the import list, as it adds more noise than useful information.

The value is that, when you have a bunch of imports, you can easily see from which package the values are coming from

2022-11-07 14:13 UTC, merged